import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 32,
    paddingBottom: 16,
  },
  containerComment: {
    flexDirection: "row",
    marginBottom: 24,
  },
  imageContainer: { marginBottom: 48 },
  image: {
    height: 240,
    backgroundColor: "#F6F6F6",
    borderRadius: 8,
    borderStyle: "solid",
    borderColor: "#E8E8E8",
    borderWidth: 1,
    marginBottom: 8,
  },
  avatarWrapper: {
    width: 28,
    height: 28,
    borderRadius: 28,
    backgroundColor: "rgba(0, 0, 0, 0.03);",
    marginRight: 16,
  },
  avatar: {
    width: 28,
    height: 28,
    borderRadius: 28,
    objectFit: "contain",
  },
  commentWrapper: {
    width: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.03)",
    borderRadius: 6,
    borderTopLeftRadius: 0,
    padding: 16,
  },
  commnetText: {
    fontFamily: "Roboto-Regular",
    marginBottom: 8,
    color: "#212121",
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 18,
    textAlign: "left",
  },
  timeText: {
    fontFamily: "Roboto-Regular",
    color: "#BDBDBD",
    fontSize: 10,
    fontWeight: "400",
    lineHeight: 12,
    textAlign: "left",
  },
  containerList: { flex: 1 },
  inputWrapper: { marginTop: 30 },
  input: {
    fontFamily: "Roboto-Regular",
    padding: 16,
    paddingRight: 90,
    height: 50,
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 100,
    borderColor: "#E8E8E8",
    backgroundColor: "#F6F6F6",
    placeholderTextColor: "#BDBDBD",
  },
  btnSubmit: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 34,
    height: 34,
    borderRadius: 100,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FF6C00",
  },
  btnSubmitText: {
    fontFamily: "Roboto-Regular",
    color: "#fff",
  },
});
export default styles;
